version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'crudshop_db'
      MYSQL_USER: 'cruduser'
      MYSQL_PASSWORD: 'crudpassword'
      MYSQL_ROOT_PASSWORD: 'crudrootpassword'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  my-db:
    driver: local